name: split_the_bill
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  random_color: ^1.0.5
  auto_size_text: ^2.1.0
  badges: ^1.2.0
  flutter_colorpicker: ^0.4.0
  get_storage: ^2.0.2
  share_plus: ^2.1.2
  smooth_page_indicator: ^0.2.3

dev_dependencies:
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launcher_icons/launcher_android.png"
  image_path_ios: "assets/launcher_icons/launcher_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: RedHat
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 300
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 900
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_native_splash:
  color: "#FCFCFC"
  image: assets/devyne_software.png
